function [] = drawTableOfMuscleConstants()
    f = figure(99);
    f.Position = [-800 400 700 400];
    t = uitable(f);
    
    titles = {'','L_o','A','M','rho','sigma_0','sigma_2','eps_1','eps_2','B','sigma_m','eps_m','b','epsDot_m)','t_i','t_p','t_s'};
    row1 = {'IA', C.muscleConstants_IA(1,1),C.muscleConstants_IA(1,2),C.muscleConstants_IA(1,3),C.muscleConstants_IA(1,4),C.muscleConstants_IA(1,5),...
                  C.muscleConstants_IA(1,6),C.muscleConstants_IA(1,7),C.muscleConstants_IA(1,8),C.muscleConstants_IA(1,9),C.muscleConstants_IA(1,10),...
                  C.muscleConstants_IA(1,11),C.muscleConstants_IA(1,12),C.muscleConstants_IA(1,13),C.muscleConstants_IA(1,14),C.muscleConstants_IA(1,16),...
                  C.muscleConstants_IA(1,16)};
    row2 = {'LCA', C.muscleConstants_LCA(1,1),C.muscleConstants_LCA(1,2),C.muscleConstants_LCA(1,3),C.muscleConstants_LCA(1,4),C.muscleConstants_LCA(1,5),...
                  C.muscleConstants_LCA(1,6),C.muscleConstants_LCA(1,7),C.muscleConstants_LCA(1,8),C.muscleConstants_LCA(1,9),C.muscleConstants_LCA(1,10),...
                  C.muscleConstants_LCA(1,11),C.muscleConstants_LCA(1,12),C.muscleConstants_LCA(1,13),C.muscleConstants_LCA(1,14),C.muscleConstants_LCA(1,16),...
                  C.muscleConstants_LCA(1,16)};
    row3 = {'PCA', C.muscleConstants_PCA(1,1),C.muscleConstants_PCA(1,2),C.muscleConstants_PCA(1,3),C.muscleConstants_PCA(1,4),C.muscleConstants_PCA(1,5),...
                  C.muscleConstants_PCA(1,6),C.muscleConstants_PCA(1,7),C.muscleConstants_PCA(1,8),C.muscleConstants_PCA(1,9),C.muscleConstants_PCA(1,10),...
                  C.muscleConstants_PCA(1,11),C.muscleConstants_PCA(1,12),C.muscleConstants_PCA(1,13),C.muscleConstants_PCA(1,14),C.muscleConstants_PCA(1,16),...
                  C.muscleConstants_PCA(1,16)};
    row4 = {'TA', C.muscleConstants_TA(1,1),C.muscleConstants_TA(1,2),C.muscleConstants_TA(1,3),C.muscleConstants_TA(1,4),C.muscleConstants_TA(1,5),...
                  C.muscleConstants_TA(1,6),C.muscleConstants_TA(1,7),C.muscleConstants_TA(1,8),C.muscleConstants_TA(1,9),C.muscleConstants_TA(1,10),...
                  C.muscleConstants_TA(1,11),C.muscleConstants_TA(1,12),C.muscleConstants_TA(1,13),C.muscleConstants_TA(1,14),C.muscleConstants_TA(1,16),...
                  C.muscleConstants_TA(1,16)};
    row5 = {'CT', C.muscleConstants_CT(1,1),C.muscleConstants_CT(1,2),C.muscleConstants_CT(1,3),C.muscleConstants_CT(1,4),C.muscleConstants_CT(1,5),...
                  C.muscleConstants_CT(1,6),C.muscleConstants_CT(1,7),C.muscleConstants_CT(1,8),C.muscleConstants_CT(1,9),C.muscleConstants_CT(1,10),...
                  C.muscleConstants_CT(1,11),C.muscleConstants_CT(1,12),C.muscleConstants_CT(1,13),C.muscleConstants_CT(1,14),C.muscleConstants_CT(1,16),...
                  C.muscleConstants_CT(1,16)};
    row6 = {'lig', C.muscleConstants_lig(1,1),C.muscleConstants_lig(1,2),C.muscleConstants_lig(1,3),C.muscleConstants_lig(1,4),C.muscleConstants_lig(1,5),...
                  C.muscleConstants_lig(1,6),C.muscleConstants_lig(1,7),C.muscleConstants_lig(1,8),C.muscleConstants_lig(1,9),C.muscleConstants_lig(1,10),...
                  C.muscleConstants_lig(1,11),C.muscleConstants_lig(1,12),C.muscleConstants_lig(1,13),C.muscleConstants_lig(1,14),C.muscleConstants_lig(1,16),...
                  C.muscleConstants_lig(1,16)};
    row7 = {'muc', C.muscleConstants_muc(1,1),C.muscleConstants_muc(1,2),C.muscleConstants_muc(1,3),C.muscleConstants_muc(1,4),C.muscleConstants_muc(1,5),...
                  C.muscleConstants_muc(1,6),C.muscleConstants_muc(1,7),C.muscleConstants_muc(1,8),C.muscleConstants_muc(1,9),C.muscleConstants_muc(1,10),...
                  C.muscleConstants_muc(1,11),C.muscleConstants_muc(1,12),C.muscleConstants_muc(1,13),C.muscleConstants_muc(1,14),C.muscleConstants_muc(1,16),...
                  C.muscleConstants_muc(1,16)};
    
    d = [titles;row1;row2;row3;row4;row5;row6;row7]';
    t.Data = d;
    t.Position = [20 20 650 350];
end